### ISSUE TITLE
App Crash Gourgeist

### ISSUE THREAD

**Issue by Ceyro** [Jerakin/Pokedex5E#563]
Clicking edit on gourgeist crashes app.

iPhone V1.12.4

This was the particular one I was having problems with.

{"level":{"evolved":[14],"caught":1,"current":18},"moves":{"Confuse Ray":{"index":3,"pp":5},"Scary Face":{"index":2,"pp":5},"Leech Seed":{"pp":5,"index":4},"Shadow Sneak":{"index":5,"pp":20},"Trick-or-Treat":{"index":1,"pp":5}},"nickname":"Hemmos","loyalty":3,"abilities":["Pickup","Frisk"],"slot":5,"statuses":[],"number":6,"species":{"current":"Gourgeist","caught":"Pumpkaboo"},"feats":["Extra Move","Resilient (CHA)","AC Up","Tough"],"exp":326000,"attributes":{"DEX":0,"CHA":0,"CON":0,"INT":0,"STR":0,"increased":{"DEX":6,"INT":0,"STR":0,"CHA":7,"WIS":0,"CON":0},"WIS":0,"nature":{"STR":-2,"AC":1}},"hp":{"max":120,"edited":false,"current":184},"id":"bf0fe63d094f8e61278bc604bd62c520","nature":"Nimble"}

**Comment by magroader** [comment]
This is not happening for me on iPhone or Jerakin on PC. I copied the pokemon, made sure it was in my party, pressed edit on it, tried changing this and saving... nothing.

Is it possible you have a fakemon package? If so which one?

**Comment by magroader** [comment]
Wait, I just got it! On iPhone.

Here's what I did:

* added the feat extra move
* removed one of the moves in the middle of the list
* I think I saved but maybe not
* I tried to remove the extra move feat but it looked like nothing happened. I did this several times.
* I think I saved but maybe not?
* I went to the moves list and they were all empty
* I added a move
* I saved
* I pressed edit
* white screen (exception loading the screen I'm sure)

**Comment by magroader** [comment]
There appears to ALSO be a bug with Gourgeist in the 1.12.4 release somehow. I'm not sure how to activate the bug, but it happens when Gourgeist is trying to find out who it evolved from. There was a bug with Pumpkaboo where it didn't know who it evolved INTO, so Gourgeist didn't know who it evolved FROM. That has since been fixed for 1.12.5, but I am fixing the code around it anyway.

The move thing is still an issue also - I believe it is related to having the Extra Move feat, then having some moves (with the last slot filled but not all slots filled, without saving) and then dropping the Extra Move feat. This also causes a crash when redrawing moves.
