### ISSUE TITLE
Pokémon Summary Screen doesn't scroll with middle mouse

### ISSUE THREAD

**Issue by TheNamesGregoryAndounuts** [Jerakin/Pokedex5E#624]
As much as I like the work that is going into this app, as a PC user I would like to make one suggestion regarding scrolling up and down the pokémon summary screen with the mouse wheel. Currently I have to drag the screen with the mouse instead of scrolling with the mouse wheel and it feels really cumbersome, can you please fix it?

**Comment by magroader** [comment]
In the 10 or so minutes I looked into this, I wasn't able to figure out how Defold and Gooey intends mousewheel to be used.

**Comment by TheNamesGregoryAndounuts** [comment]
Well maybe try asking them?

**Comment by magroader** [comment]
Closing because this Duplicates #521 

@Jerakin had looked into this and found that if we just inserted it, the screen would move waaaay too slow.

He added a task for the low-level library we are using to improve things (https://github.com/britzl/gooey/issues/63) Editing the lower-level library is a more complex affair unfortunately, which is why this wasn't a quick fix.
